### ISSUE TITLE
Deviation of 2D keypoints

### ISSUE THREAD

**Issue by limgm** [lmb-freiburg/freihand#1]
Thank you for releasing the dataset!

I have tried to run the view_samples.py on the first few images of the training data and found that some of the 2D keypoints seem to deviate from the finger.

May I check if the below deviations are expected? Below are some examples from the training data:

Index 0
![Figure_0](https://user-images.githubusercontent.com/22131931/65814232-a742b900-e211-11e9-937e-294759280a41.png)
Index 3
![Figure_3](https://user-images.githubusercontent.com/22131931/65814233-aa3da980-e211-11e9-93f0-474938801e9e.png)
Index 5
![Figure_5](https://user-images.githubusercontent.com/22131931/65814236-ac076d00-e211-11e9-8ab7-e1bb33710356.png)
Index 8
![Figure_8](https://user-images.githubusercontent.com/22131931/65814237-ad389a00-e211-11e9-803c-a277242dc12b.png)
Index 10
![Figure_10](https://user-images.githubusercontent.com/22131931/65814239-af025d80-e211-11e9-88a1-d7db0cdd3be8.png)
Index 13
![Figure_13](https://user-images.githubusercontent.com/22131931/65814242-b0cc2100-e211-11e9-8fa4-7e6391c86332.png)

**Comment by zimmerm** [comment]
Thank you for you interest in our work.
Unfortunately, there is some expected deviation, which results from different sources of error that accumulate over the fitting procedure. The resulting offset is some mixture of imperfection in camera calibration, the fact that I use predictions and (noisy) human annotation to find one MANO fit for image evidence from 8 cameras. Naturally, there are some cameras where the shape fits perfectly and some where it is a little bit worse.
Additionally, there is some issue with the current annotation, which stems from the fact that I developed the dataset with an older version of the MANO model, which is not supported anymore. And using the given annotations with the new model yields different results. I'm currently working on an update to accommodate the version change.
