### ISSUE TITLE
Codalab Malfunctioning 

### ISSUE THREAD

**Issue by hongsukchoi** [lmb-freiburg/freihand#16]
FreiHAND competition site is malfunctioning.
 I submitted multiple result files(*.zip) and none of them are processed for hours.
This phenomenon has been shown since yesterday. 

I wish you to check this, and plz look at the attach for the details.
Thank you.

**Comment by zimmerm** [comment]
Hello,

this is most likely a failure on the Codalab side. Probably, their servers are overloaded and it will take some time for them to fix the issue again. Unfortunately, this happened before but its out of my powers to deal with.

Chris
