### ISSUE TITLE
How to participate in  FreiHAND challenge

### ISSUE THREAD

**Issue by reshow** [lmb-freiburg/freihand#18]
Hello, I want to verify my method on the evaluation dataset, but I didn't get a reply within a few days after I submitted my application to participate in the competition in codalab. How long do I probably need to wait?. Appreciate for your help.

**Comment by wqdfj** [comment]
Hello,  have you entered the competition? I submitted the application a week ago,  but I haven't received a reply yet.

**Comment by tccfree** [comment]
> Hello, I want to verify my method on the evaluation dataset, but I didn't get a reply within a few days after I submitted my application to participate in the competition in codalab. How long do I probably need to wait?. Appreciate for your help.

Hello，when do you get the reply?  I have the same issue...

**Comment by wkailiu** [comment]
@tccfree 
Have you passed the verification? How many days do you need to wait?
