### ISSUE TITLE
Computation of the F Score

### ISSUE THREAD

**Issue by zhipeng-fan** [lmb-freiburg/freihand#31]
Hi! 

I got a quick question regarding computing the precision and recall to get the F score in the evaluation. I see in your original paper you refer to [1] for the details.  But for pose estimation, the point in Reconstruction has an exact match in GT, while in the general 3D reconstruction task in [1], the relationship between the reconstructed point cloud and ground truth point cloud is not clear. I guess that's why in [1] they define the distance based on the closest point like chamfer distance. I was wondering for Freihand evaluation, are we following [1] exactly or define distance based on the known match relationships?

Thanks!

[1] Tanks and Temples: Benchmarking Large-Scale Scene Reconstruction

**Comment by zimmerm** [comment]
I'm following the definition exactly.
