### ISSUE TITLE
Issue about MANO parameter 

### ISSUE THREAD

**Issue by CVStack** [lmb-freiburg/freihand#34]
Thank you sharing the code and dataset. Your dataset is very helpful to my research.

I have a question about mano annotation file.

I used the first 48 of the 61 parameter as mano pose parameter and visualize one mano sample and image. 

But it is not same. In addition to this, there were several other cases.

How can i solve this problem?

Thank you.

![image](https://user-images.githubusercontent.com/38209962/184773519-c93b0054-6245-4de7-b39d-a334798d4753.png)

**Comment by i-dont-know-how-to-sign-up** [comment]
Did you solve it？ I came into the same issue
