### ISSUE TITLE
Code for MANO fitting

### ISSUE THREAD

**Issue by StevenZzz07** [lmb-freiburg/freihand#35]
Hello, thanks for ur outstanding work. This dataset help me a lot in research. Now I am working on 3D hand reconstruction and want to build my own 3D hand dataset. Thus, I wonder if you can release the code for fitting the MANO model into multi-view images by optimization. 

Thanks in advance!!!

**Comment by wadhwasahil** [comment]
I am also looking for the same. @zimmerm

**Comment by zimmerm** [comment]
The code is not in a publishable state and unfortunately I have left academia and will not find time to clean it up. Sorry about that.
