### ISSUE TITLE
Migration to new CodaLab?

### ISSUE THREAD

**Issue by lywcn** [lmb-freiburg/freihand#36]
Hi, all

Thank you so much for your dataset and competitions! 

It seems the old CodaLab server is retiring and I am wondering if you are able to migrate the current competition to the new server?

https://competitions.codalab.org/competitions/21238   --> CodaLab competition 21238 is no longer accepting new submissions

If you are working on the migration, please let us know. Thank you!

John

**Comment by lsycool** [comment]
+1

**Comment by indigo-99** [comment]
I have the same issue!

**Comment by zimmerm** [comment]
I'll try to look into it, but you are actually able to run the code locally yourselves. I have released the evaluation dataset and the evaluation code itself was always released:
https://github.com/lmb-freiburg/freihand#newexclamation
