### ISSUE TITLE
Codalab competition

### ISSUE THREAD

**Issue by heartStrive** [lmb-freiburg/freihand#37]
Hi,
    I applied to join the freiHand competition, but my request was never reviewed.
    Could you please approve my request as soon as possible?
Thank you very much！

**Comment by liumc14** [comment]
Could you ask how to write pred.py? I'm just doing my homework, not participating in the competition. Thank you

**Comment by zimmerm** [comment]
https://github.com/lmb-freiburg/freihand/issues/36#issuecomment-1269409302
