### ISSUE TITLE
needs to get results on the FreiHAND dataset

### ISSUE THREAD

**Issue by lcaikk1314** [lmb-freiburg/freihand#39]
Hello, I have a new algorithm that needs to get results on the FreiHAND dataset, However, "Your request to participate in this challenge has been received and a decision is pending." has been displayed for a week. Could you please help pass it,Thank you very much!

**Comment by zimmerm** [comment]
https://github.com/lmb-freiburg/freihand/issues/36#issuecomment-1269409302
