### ISSUE TITLE
How to divide the data set into two parts based on the presence or absence of objects?

### ISSUE THREAD

**Issue by TerenceCYJ** [lmb-freiburg/freihand#5]

**Comment by TerenceCYJ** [comment]
Hi, 
Thank you for the awesome dataset. There is a question about the dataset. Since object presents in some images, how can I distinguish those images with others that only have hand?
Thank you! Look forward to your reply!

**Comment by zimmerm** [comment]
This information is not available in the currently published version, but will be contained in the next release.
